-- new_bi.dcar_ai_body_relation definition

CREATE TABLE `dcar_ai_body_relation` (
                                         `id` bigint unsigned NOT NULL AUTO_INCREMENT,
                                         `code` varchar(255) DEFAULT NULL COMMENT '智能体编码',
                                         `relation_id` bigint DEFAULT NULL COMMENT '关联id-表ormodel',
                                         `relation_type` int DEFAULT NULL COMMENT '关联类型0-关联事实表1-关联分析模型',
                                         `created_by` bigint NOT NULL COMMENT '创建人',
                                         `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                         `updated_by` bigint NOT NULL COMMENT '修改人',
                                         `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                         PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COMMENT='GBI智能体即席模式关联数据表';
CREATE TABLE `dcar_ai_body` (
                                `id` int unsigned NOT NULL AUTO_INCREMENT,
                                `code` varchar(255) DEFAULT NULL COMMENT '标识编码',
                                `name` varchar(255) DEFAULT NULL COMMENT '智能体名称',
                                `interaction_mode` int DEFAULT NULL COMMENT '交互模式0-多维分析1-即席分析',
                                `theme_code` varchar(255) DEFAULT NULL COMMENT '关联主题编码',
                                `authorize_strategy` int DEFAULT '0' COMMENT '授权策略(0-私有 1-公开 2-自定义)',
                                `created_by` bigint NOT NULL COMMENT '创建人',
                                `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                `updated_by` bigint NOT NULL COMMENT '修改人',
                                `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                `hot_words` json DEFAULT NULL COMMENT '语音热词',
                                `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
                                PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COMMENT='智能体';

CREATE TABLE `ai_body_knowledge_info` (
                                          `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
                                          `ai_body_id` bigint DEFAULT NULL COMMENT '智能体主键',
                                          `knowledge_element` text CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '单条知识库内容',
                                          `knowledge_alias` json DEFAULT NULL COMMENT '知识库别名',
                                          `created_by` bigint NOT NULL COMMENT '创建人',
                                          `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                          `updated_by` bigint NOT NULL COMMENT '修改人',
                                          `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                          PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC COMMENT='智能体单条知识库';

-- descartes.olap_basic_pro definition
CREATE TABLE `olap_basic_pro` (
                                  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                  `tenant_id` bigint DEFAULT '1' COMMENT '租户 ID',
                                  `category` tinyint NOT NULL DEFAULT '1' COMMENT '1-维度 2-指标',
                                  `key_str` varchar(255) DEFAULT NULL COMMENT '唯一 key 用于校验名称重复',
                                  `chinese_name` varchar(255) DEFAULT NULL COMMENT '中文名称',
                                  `standard_name` varchar(255) DEFAULT NULL COMMENT '标准名称',
                                  `alias` varchar(255) DEFAULT NULL COMMENT '别名',
                                  `english_name` varchar(255) DEFAULT NULL COMMENT '英文名称',
                                  `abbreviation` text COMMENT '缩写',
                                  `classification_label` varchar(255) DEFAULT NULL COMMENT '分类标签',
                                  `classification_label_name` varchar(255) DEFAULT NULL COMMENT '分类标签名称',
                                  `olap_label` varchar(255) DEFAULT 'olapcommon' COMMENT 'OLAB 标签',
                                  `olap_label_name` varchar(255) DEFAULT '通用' COMMENT 'OLAB 标签名称',
                                  `data_type` varchar(500) DEFAULT NULL COMMENT '数据类型',
                                  `data_source_type` tinyint DEFAULT '1' COMMENT '1-公司 -1-个人',
                                  `status` tinyint NOT NULL DEFAULT '0' COMMENT '0-草稿 1-审批中 2-已上线 3-已下线',
                                  `principal` bigint DEFAULT NULL COMMENT '负责人',
                                  `principal_name` varchar(50) DEFAULT NULL COMMENT '负责人名字',
                                  `principal_email` varchar(50) DEFAULT NULL COMMENT '负责人邮箱',
                                  `approver` bigint DEFAULT NULL COMMENT '审批人',
                                  `approver_name` varchar(50) DEFAULT NULL COMMENT '审批人名字',
                                  `approver_email` varchar(50) DEFAULT NULL COMMENT '审批人邮箱',
                                  `is_show` varchar(2) DEFAULT '1' COMMENT '是否显示 1-是 0-否',
                                  `created_by` varchar(256) NOT NULL COMMENT '创建人',
                                  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                  `updated_by` varchar(256) NOT NULL COMMENT '修改人',
                                  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                  PRIMARY KEY (`id`),
                                  KEY `idx_tenant_category_status` (`tenant_id`,`category`,`status`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='指标维度基础信息表';
-- descartes.olap_basic_pro_dimension definition

CREATE TABLE `olap_basic_pro_dimension` (
                                            `id` bigint NOT NULL AUTO_INCREMENT,
                                            `olap_basic_pro_id` bigint NOT NULL COMMENT '指标维度基础信息表id',
                                            `dimension_type` tinyint NOT NULL DEFAULT '1' COMMENT '维度类型 1:标准维 2:杂项维',
                                            `high_level_flag` tinyint NOT NULL DEFAULT '2' COMMENT '是否是高基维 1:是 2:否',
                                            `database_table_id` bigint DEFAULT NULL COMMENT '库表id',
                                            `database_table_name` varchar(255) DEFAULT NULL COMMENT '库表名',
                                            `column_id` bigint DEFAULT NULL COMMENT '字段id',
                                            `column_key` varchar(255) DEFAULT NULL COMMENT '字段key',
                                            `column_name` varchar(255) DEFAULT NULL COMMENT '字段名',
                                            `dimension_translation` text COMMENT '维值翻译(json格式)',
                                            `value_field_id` bigint DEFAULT NULL COMMENT '值id',
                                            `value_field_key` varchar(255) DEFAULT NULL COMMENT '值key',
                                            `value_field_name` varchar(255) DEFAULT NULL COMMENT '值名',
                                            `caliber_description` varchar(255) DEFAULT NULL COMMENT '维度说明，口径描述',
                                            `monitor` varchar(4) DEFAULT 'N' COMMENT '是否监控',
                                            `dim_filter` text,
                                            `time_dynamic` varchar(5) DEFAULT NULL,
                                            `partition_field` varchar(255) DEFAULT NULL,
                                            `partition_format` varchar(30) DEFAULT NULL,
                                            `is_attributing` tinyint NOT NULL DEFAULT '0' COMMENT '是否参与归因分析 0-否 1-是',
                                            PRIMARY KEY (`id`) USING BTREE,
                                            UNIQUE KEY `uniq_idx_olap_basic_pro_id` (`olap_basic_pro_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11774 DEFAULT CHARSET=utf8mb3 ROW_FORMAT=DYNAMIC COMMENT='指标平台维度基础信息(附属于olap_basic_pro)';

-- descartes.olap_basic_pro_indicator definition

CREATE TABLE `olap_basic_pro_indicator` (
                                            `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                            `olap_basic_pro_id` bigint NOT NULL COMMENT '关联 olap_basic_pro.id',
                                            `business_theme` varchar(255) NOT NULL DEFAULT '' COMMENT '业务主题',
                                            `business_theme_name` varchar(255) NOT NULL DEFAULT '' COMMENT '业务主题名称',
                                            `business_theme_id` bigint DEFAULT NULL COMMENT '业务主题 ID',
                                            `business_line` varchar(255) NOT NULL DEFAULT '' COMMENT '业务线',
                                            `business_line_name` varchar(255) NOT NULL DEFAULT '' COMMENT '业务线名称',
                                            `business_process_id` bigint DEFAULT NULL COMMENT '业务过程 ID',
                                            `business_root` varchar(255) NOT NULL DEFAULT '' COMMENT '词根',
                                            `business_root_name` varchar(255) NOT NULL DEFAULT '' COMMENT '词根名称',
                                            `decorate_word` text COMMENT '修饰词 JSON 数组',
                                            `time_period` varchar(255) DEFAULT '' COMMENT '时间周期',
                                            `time_period_name` varchar(255) DEFAULT '' COMMENT '时间周期名称',
                                            `caliber_description` varchar(255) NOT NULL COMMENT '口径描述',
                                            `calculated_production` text COMMENT '计算指标公式 JSON {formula,mapping[{symbol,metricId,code,name}]}',
                                            `calculated_production_check` text COMMENT '计算指标公式复核',
                                            `derivative_production` text COMMENT '衍生指标公式 JSON',
                                            `derivative_production_check` text COMMENT '衍生指标公式复核',
                                            `unit` varchar(255)   DEFAULT null COMMENT '元、角、分、kwh、吨、千克等',
                                            `decimal_places` tinyint DEFAULT NULL COMMENT '小数点位数：0-无 1-.0 2-.00 3-.000 4-.0000，为NULL时使用原始值',
                                            `relation_indicators` text COMMENT '关联指标 ID JSON 数组',
                                            `threshold_rule` varchar(512) DEFAULT NULL COMMENT '阈值规则',
                                            `null_handling` varchar(512) DEFAULT NULL COMMENT '空值处理',
                                            `monitor_level` varchar(10) DEFAULT '' COMMENT '监控级别',
                                            `warning_info` text COMMENT '预警信息',
                                            `authorize_strategy` int DEFAULT '2' COMMENT '1-公开 2-私有 3-自定义',
                                            `oauth_group` varchar(16) DEFAULT '' COMMENT '权限分组',
                                            `visits_num` int DEFAULT '0' COMMENT '访问次数',
                                            `workflow_id` bigint DEFAULT NULL COMMENT '审批流 ID',
                                            `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户 ID',
                                            `created_by` varchar(256) NOT NULL COMMENT '创建人',
                                            `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                            `updated_by` varchar(256) NOT NULL COMMENT '修改人',
                                            `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                            PRIMARY KEY (`id`),
                                            UNIQUE KEY `uniq_basic_pro` (`olap_basic_pro_id`),
                                            KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='指标扩展信息表';

CREATE TABLE `olap_data_model` (
                                   `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                   `name` varchar(128) NOT NULL COMMENT '模型名称',
                                   `source_id` bigint NOT NULL COMMENT '关联 meta_data_source.id',
                                   `fact_table_id` bigint NOT NULL COMMENT '事实表 ID 关联 olap_table_pro',
                                   `description` varchar(512) DEFAULT NULL COMMENT '模型说明',
                                   `status` tinyint NOT NULL DEFAULT '0' COMMENT '1-启用 0-停用',
                                   `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户 ID',
                                   `created_by` bigint NOT NULL COMMENT '创建人',
                                   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                   `updated_by` bigint NOT NULL COMMENT '修改人',
                                   `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                   PRIMARY KEY (`id`),
                                   KEY `idx_source` (`source_id`),
                                   KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据模型表';

CREATE TABLE `olap_data_model_dimension` (
                                             `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                             `model_id` bigint NOT NULL COMMENT '关联 olap_data_model.id',
                                             `dim_table_id` bigint NOT NULL COMMENT '维度表 ID 关联 olap_table_pro',
                                             `join_type` varchar(16) NOT NULL DEFAULT 'LEFT JOIN' COMMENT 'LEFT JOIN / INNER JOIN',
                                             `fact_fk_column` varchar(256) NOT NULL COMMENT '事实表关联字段 列名',
                                             `dim_pk_column` varchar(256) NOT NULL COMMENT '维度表关联字段 列名',
                                             `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户 ID',
                                             `created_by` bigint NOT NULL COMMENT '创建人',
                                             `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                             `updated_by` bigint NOT NULL COMMENT '修改人',
                                             `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                             PRIMARY KEY (`id`),
                                             KEY `idx_model` (`model_id`),
                                             KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='模型-维度关联表';

-- descartes.olap_table_pro definition
CREATE TABLE `olap_table_pro` (
                                  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                  `plus_id` bigint DEFAULT NULL COMMENT '关联 meta_table.id',
                                  `db_name` varchar(100) DEFAULT NULL COMMENT '库名',
                                  `tb_name` varchar(100) DEFAULT NULL COMMENT '表名',
                                  `cn_name` varchar(50) DEFAULT NULL COMMENT '表中文名',
                                  `tb_cn_name` varchar(100) DEFAULT NULL COMMENT '表中文名冗余',
                                  `note` varchar(100) DEFAULT NULL COMMENT '表注释',
                                  `theme` varchar(100) DEFAULT NULL COMMENT '主题',
                                  `theme_key` varchar(100) DEFAULT NULL COMMENT '主题 key',
                                  `type` varchar(100) NOT NULL COMMENT '业务类型',
                                  `type_key` varchar(100) NOT NULL COMMENT '业务类型 key：fact/dim',
                                  `model_type` smallint DEFAULT '0' COMMENT '0-OLAP模型 1-临查模型',
                                  `tb_type` varchar(100) DEFAULT '0' COMMENT '存储类型',
                                  `tb_type_key` varchar(100) DEFAULT '0' COMMENT '0-物理表 1-视图',
                                  `status` smallint NOT NULL COMMENT '0-删除 1-审批中 2-待上线 3-已上线 4-已下线 5-已驳回',
                                  `owner_name` varchar(100) DEFAULT NULL COMMENT '负责人姓名',
                                  `owner_email` varchar(100) DEFAULT NULL COMMENT '负责人邮箱',
                                  `owner_account` varchar(100) DEFAULT NULL COMMENT '负责人账号',
                                  `modify_name` varchar(100) DEFAULT NULL COMMENT '更新人姓名',
                                  `modify_email` varchar(255) DEFAULT NULL COMMENT '更新人 email',
                                  `modify_account` varchar(100) DEFAULT NULL COMMENT '修改人账号',
                                  `created_by` varchar(128) NOT NULL COMMENT '创建人',
                                  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                  `updated_by` varchar(128) NOT NULL COMMENT '修改人',
                                  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                  `product_time` varchar(20) DEFAULT NULL COMMENT '产出时间',
                                  `update_type` tinyint DEFAULT '0' COMMENT '0-离线 1-实时累计 2-实时时段',
                                  `sync_data_type` tinyint NOT NULL DEFAULT '1' COMMENT '0-直连 1-抽取',
                                  `connect_type` varchar(100) NOT NULL DEFAULT 'lingxi' COMMENT '连接类型',
                                  `engine_infos` text COMMENT '引擎信息',
                                  `engine_id` bigint DEFAULT NULL COMMENT '引擎 ID',
                                  `data_source_type` tinyint DEFAULT '1' COMMENT '1-公司 -1-个人',
                                  `cube` varchar(4) DEFAULT 'N' COMMENT '是否 cube',
                                  `decision` varchar(2) DEFAULT 'Y' COMMENT '是否参与决策',
                                  `monitor_level` varchar(4) DEFAULT 'P0' COMMENT '监控等级',
                                  `required_dim_ids` varchar(300) DEFAULT NULL COMMENT '指定维度',
                                  `add_field_type` smallint DEFAULT '1' COMMENT '0-已有库表 1-灵犀元数据',
                                  `business_type` varchar(255) DEFAULT NULL COMMENT '表业务类型',
                                  `business_process_id` bigint DEFAULT NULL COMMENT '业务过程 ID',
                                  `etl_id` bigint DEFAULT NULL COMMENT 'ETL 任务 ID',
                                  `etl_name` varchar(255) DEFAULT NULL COMMENT 'ETL 任务名',
                                  `etl_status` smallint DEFAULT NULL COMMENT 'ETL 状态',
                                  `etl_error` text COMMENT 'ETL 创建 msg',
                                  `etl_batch` varchar(100) DEFAULT NULL COMMENT 'ETL 批次号',
                                  `query_sql` longtext COMMENT '实时查询 SQL',
                                  `view_sql` longtext COMMENT '视图 SQL',
                                  `query_use_cache` tinyint DEFAULT '1' COMMENT '0-不走缓存 1-走缓存',
                                  `tenant_id` bigint DEFAULT '1' COMMENT '租户 ID',
                                  PRIMARY KEY (`id`),
                                  KEY `idx_plus` (`plus_id`),
                                  KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='分析数据表';


CREATE TABLE `olap_table_field_mapping` (
                                            `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                            `table_id` bigint DEFAULT NULL COMMENT '关联 olap_table_pro.id',
                                            `field_key` varchar(255) DEFAULT NULL COMMENT '原表字段名',
                                            `field_name` varchar(255) DEFAULT NULL COMMENT '原表字段中文名',
                                            `basic_id` bigint DEFAULT NULL COMMENT '关联 olap_basic_pro.id',
                                            `basic_key` varchar(255) DEFAULT NULL COMMENT '指标维度的key',
                                            `basic_type` varchar(100) DEFAULT NULL COMMENT '类型：维度/维度id/指标/分区字段/其他',
                                            `basic_type_key` varchar(100) DEFAULT NULL COMMENT '类型 key：dim/dimid/index/other/pf',
                                            `basic_name` varchar(100) DEFAULT NULL COMMENT '指标或维度中文名称',
                                            `field_type` varchar(100) DEFAULT NULL COMMENT '字段格式类型',
                                            `field_type_name` varchar(100) DEFAULT NULL COMMENT '字段格式类型名称',
                                            `field_note` varchar(500) DEFAULT NULL COMMENT '字段注释',
                                            `is_customize` int DEFAULT '0' COMMENT '0-否 1-是',
                                            `pf_status` smallint DEFAULT '0' COMMENT '是否分区字段 0-否 1-是',
                                            `summary` varchar(100) DEFAULT NULL COMMENT '聚合函数 sum/count/count distinct/avg/time_format',
                                            `summary_key` varchar(100) DEFAULT NULL COMMENT '聚合函数 key',
                                            `expression` varchar(500) DEFAULT NULL COMMENT '字段级转换表达式',
                                            `inner_field_key` varchar(255) DEFAULT NULL COMMENT '映射的 field_key',
                                            `look_back_mapping_ids` longtext COMMENT '上溯关联 IDs',
                                            `look_back_mapping_names` longtext COMMENT '上溯关联显示信息',
                                            `look_back_flag` int NOT NULL DEFAULT '1' COMMENT '0-部分汇总 1-可汇总',
                                            `height` int NOT NULL DEFAULT '1000' COMMENT '排序字段',
                                            `engine_infos` varchar(2000) DEFAULT NULL COMMENT '引擎信息',
                                            `status` smallint DEFAULT '1' COMMENT '0-删除 1-有效 2-待生效',
                                            `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户 ID',
                                            `created_by` varchar(128) NOT NULL COMMENT '创建人',
                                            `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                            `updated_by` varchar(128) NOT NULL COMMENT '修改人',
                                            `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                            `date_format` varchar(32) DEFAULT NULL COMMENT '源字段日期格式，如yyyyMMdd、yyyy-MM-dd，NULL 表示标准日期类型',
                                            PRIMARY KEY (`id`),
                                            KEY `idx_table` (`table_id`),
                                            KEY `idx_basic` (`basic_id`),
                                            KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='元数据字段映射表';


CREATE TABLE `meta_data_source` (
                                    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                    `name` varchar(128) NOT NULL COMMENT '数据源别名',
                                    `db_type` varchar(32) NOT NULL COMMENT '数据库类型 MySQL/PostgreSQL/Oracle/达梦/GaussDB/ClickHouse',
                                    `host` varchar(256) NOT NULL COMMENT '主机地址',
                                    `port` int NOT NULL COMMENT '端口号',
                                    `username` varchar(128) NOT NULL COMMENT '账号',
                                    `password` varchar(256) NOT NULL COMMENT '密码明文存储',
                                    `default_db` varchar(128) NOT NULL COMMENT '数据库/SID/模式名',
                                    `schema_name` varchar(128) DEFAULT NULL COMMENT 'Schema（Oracle/PG/GaussDB 选填）',
                                    `jdbc_url` varchar(512) DEFAULT NULL COMMENT 'JDBC 连接 URL（后端自动生成，前端只读）',
                                    `status` tinyint NOT NULL DEFAULT '1' COMMENT '1-启用 0-停用',
                                    `tenant_id` bigint NOT NULL COMMENT '租户 ID',
                                    `created_by` bigint NOT NULL COMMENT '创建人',
                                    `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                    `updated_by` bigint NOT NULL COMMENT '修改人',
                                    `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                    PRIMARY KEY (`id`),
                                    KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='数据源注册表';


CREATE TABLE `meta_table` (
                              `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                              `source_id` bigint NOT NULL COMMENT '关联 meta_data_source.id',
                              `tenant_id` bigint NOT NULL COMMENT '租户 ID',
                              `schema_name` varchar(128) NOT NULL COMMENT 'Schema/Database 名',
                              `table_name` varchar(256) NOT NULL COMMENT '表名',
                              `table_comment` varchar(512) DEFAULT NULL COMMENT '表注释',
                              `row_count_estimate` bigint DEFAULT NULL COMMENT '预估行数',
                              `last_collected_at` datetime DEFAULT NULL COMMENT '最近采集时间',
                              `created_by` bigint NOT NULL COMMENT '创建人',
                              `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                              `updated_by` bigint NOT NULL COMMENT '修改人',
                              `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                              PRIMARY KEY (`id`),
                              KEY `idx_source` (`source_id`),
                              KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='元数据-表';

CREATE TABLE `olap_indicator_group` (
                                        `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                        `group_code` varchar(128) NOT NULL COMMENT '组合编码',
                                        `group_name` varchar(128) NOT NULL COMMENT '组合名称',
                                        `subject_domain` varchar(128) DEFAULT NULL COMMENT '主题域',
                                        `description` varchar(512) DEFAULT NULL COMMENT '描述',
                                        `owner` bigint DEFAULT NULL COMMENT '负责人',
                                        `status` tinyint NOT NULL DEFAULT '0' COMMENT '0-草稿 1-审批中 2-已上线 3-已下线',
                                        `version` int DEFAULT '1' COMMENT '版本号',
                                        `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户 ID',
                                        `created_by` bigint NOT NULL COMMENT '创建人',
                                        `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                        `updated_by` bigint NOT NULL COMMENT '修改人',
                                        `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                        PRIMARY KEY (`id`),
                                        KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='指标组合主表';
CREATE TABLE `olap_group_item` (
                                   `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
                                   `group_id` bigint NOT NULL COMMENT '关联 olap_indicator_group.id',
                                   `item_type` varchar(32) NOT NULL COMMENT 'dimension/atomic_metric/calculated_metric/derived_metric/indicator_group',
                                   `object_id` bigint NOT NULL COMMENT '关联 olap_basic_pro.id 或 olap_indicator_group.id',
                                   `display_name` varchar(128) DEFAULT NULL COMMENT '展示名称',
                                   `display_order` int NOT NULL DEFAULT '0' COMMENT '展示顺序',
                                   `is_required` tinyint DEFAULT '0' COMMENT '是否必选 0-否 1-是',
                                   `is_default_visible` tinyint DEFAULT '1' COMMENT '是否默认展示 0-否 1-是',
                                   `format_type` varchar(32) DEFAULT NULL COMMENT '格式类型',
                                   `unit` varchar(32) DEFAULT NULL COMMENT '单位',
                                   `default_sort` varchar(8) DEFAULT NULL COMMENT '默认排序 ASC/DESC',
                                   `default_filter` varchar(512) DEFAULT NULL COMMENT '默认筛选条件 JSON',
                                   `remark` varchar(512) DEFAULT NULL COMMENT '备注',
                                   `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户 ID',
                                   `created_by` bigint NOT NULL COMMENT '创建人',
                                   `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                   `updated_by` bigint NOT NULL COMMENT '修改人',
                                   `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
                                   PRIMARY KEY (`id`),
                                   KEY `idx_group` (`group_id`),
                                   KEY `idx_tenant` (`tenant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='指标组合项表';